### PR TITLE
Revert #446 changes

### PR DESCRIPTION
**Pull request by stech11845**
### Requirements for Contributing Documentation

* Fill out the template below. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* The pull request must only contribute documentation (for example, markdown files or API docs). To contribute other changes, you must use a different template. You can see all templates at <https://github.com/atom/.github/tree/master/.github/PULL_REQUEST_TEMPLATE>.

### Description of the Change
Reverts #446.

### Release Notes
N/A

### CODE REVIEW

**Review by aminya — CHANGES_REQUESTED** [review]
I prefer the current design because the more important buttons come first. The badges are not useful for most people.

**Comment by stech11845** [comment]
> I prefer the current design because the more important buttons come first. The badges are not useful for most people.

What? @ElectronicsArchiver said it's ugly, so I made this. So I don't agree why.

**Comment by aminya** [comment]
Most people want to download Atom and use it (used to be two million people). We only have a handful of developers who build Atom.

**Comment by ElectronicsArchiver** [comment]
*Well maintainers have the last word..*

Good thing that this is only a maintenance
project and Atoms UI has long been finished~

**Comment by ElectronicsArchiver** [comment]
> Most people want to download Atom and use it (used to be two million people). We only have a handful of developers who build Atom.

And thats why the building button is on the same level as the installation button?
Not a great argument if you ask me..

**Comment by stech11845** [comment]
> I prefer the current design because the more important buttons come first. The badges are not useful for most people.

@aminya The badges _**are**_ useful because they guide you to helpful links.

**Comment by icecream17** [comment]
I also prefer the current design fwiw, just because it looks nicer to me.
The badges don't seem smushed together at all, in fact having them together feels more connected?

I think maybe it's just the size of everything; the banner then the h1 then the badges seems more pleasing than putting badges between header and banner, and in general more important things like the title go before subtitle/content:

image

Also the badges just happen to be in a funnel shape.

Maybe the ugly thing about it is the spacing? (header->badge smaller than badge->badge whitespace)
image

Note that my opinion isn't very strong on this; it isn't very clear to me that this is an improvement, unlike say, regular links to badges.

I'll just let consensus build about this though, since I don't feel like giving more effort on the readme

**Comment by ElectronicsArchiver** [comment]
You could also just put them before the banner and 'out of the way', thus bringing the focus on the `important` things.

**Pull request closed without merging**
