### PR TITLE
feat: update babel to 7

### PR DESCRIPTION
**Pull request by aminya**
Copied from https://github.com/atom/atom/pull/21623:

### Description of the Change

This upgrades babel to babel 7. 

This PR is the result of two years of effort and trying. 
I had to fix electron-link so:
- it can support parsing new JavaScript: https://github.com/atom/electron-link/pull/20
- it can bundle lazy require https://github.com/atom/electron-link/pull/27 -> This is merged but not registered. That's why I am using @aminya/electron-link
- [and some](https://github.com/atom/electron-link/pull/26), [other changes](https://github.com/atom/electron-link/pull/31)

I developed two plugins specifically for Atom to support its special situation:
- [babel-preset-atomic](https://github.com/atom-ide-community/babel-preset-atomic) this is the plugin that includes all the other babel plugins. It has babel-preset (configured for Electron 6), babel-flow, babel-react, and many of the proposal plugins that are equivalents of the similar plugins included in the deprecated stage-0 package (e.g., class properties, private properties, decorators, private methods, etc.). It adds some of the new proposal plugins, such as optional chaining. It also allows us to do compile-time calculations using codegen and prevel.

See the full list of plugins that babel-preset-atomic has [in this package.json](https://github.com/atom-ide-community/babel-preset-atomic/blob/dd2843291989ea99e184e7c9279b57c05c7f6412/package.json#L19).

- [babel-plugin-transform-not-strict](https://github.com/atom-ide-community/babel-plugin-transform-not-strict): this removes 'use strict' whenever 'use babel' (or similar triggers) are used. This is because Babel 6/7 now assumes all the ES modules (those who use `import/export`) are strict by default. However, this breaks some of the Atom packages because they do non-strict things in ES modules. So, I developed this plugin to remove 'use strict' when the triggers are used. I have baked a feature in this plugin that allows removing 'use strict' selectively by adding 'not strict' directive. Ultimately, we should add this 'not strict' to any file that uses JS loosely in ES modules. An example of this is `spec/update-process-env-spec.js`

There are two move plugins included for backward compatibility:
- [babel-add-module-exports](https://github.com/lijunle/babel-plugin-add-module-exports): this plugin circumvents the fact that ES modules export default by "default" keyword. This means we need to call `require().default` to consume them. This plugin works in combination with transform-not-strict to add `module.exports=` to the packages that export default things that should have been named exports. For the packages' root, I already made [another PR that adds support for both cases](https://github.com/atom/atom/pull/21112), but we cannot patch require for the packages' internal requires as we only have access to the root.

- [@babel/plugin-transform-reserved-words](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-reserved-words) that allows the uses of the old banned keywords such as `package` or `debugger`.

Fixed the loose usage of JavaScript in the following packages:
 - https://github.com/atom-community/find-and-replace/pull/5 	

### Benefits
This PR has several benefits:
- Allows building Atom with Node 12.16 or above (see [this issue](https://github.com/atom/atom/issues/21091)). This will be crucial for upgrading Electron.
- This allows using the new babel plugins (e.g., optional chaining) just by including `"use babel"`. 
- This also enhances the performance of babel compiling. 

### Previous attempts
https://github.com/atom-ide-community/atom/pull/67
https://github.com/atom/atom/pull/20965

### Release Notes
- Updates babel to babel 7 🎉

### CODE REVIEW

**Comment by DeeDeeG** [comment]
If I understand it correctly, this makes newer versions of Node able to build Atom; I think babel 7 has fixes for use with more-recent Node versions.

https://github.com/atom/atom/issues/21091

> Affected versions of Node:
> - 12.17.0 and newer (can use 12.16.x and older)
> - 13.2.0 and newer (can use 13.0.0? I think.)
> - 14.0.0 and newer (all versions 14.0.0 and newer are affected).

**Comment by aminya** [comment]
Yes. Check my comment here: https://github.com/atom/atom/issues/21091#issuecomment-663996110

**Comment by aminya** [comment]
I did not notice that we have babel-spec too 😄. I guess I need to update that as well.

**Comment by aminya** [comment]
Async to generator plugin is not working nicely. I am going to remove it. I also will use our atomic babel preset instead of this whole thing. That is easier to maintain.

**Comment by aminya** [comment]
NPM's git installer acts weird. Why it can't install some of the packages?!

**Comment by DeeDeeG** [comment]
FWIW, I believe it clones the git dependency, tries to install the dependency in a temp folder (if there is a `package-lock.json` checked into the repo of the git dependency, this is used! Not sure why.) and then... throws out everything from the temp folder and just uses the package.json from the git dependency?? Or something? It's a very confusing process.

And as far as I can tell, this causes bizarre errors unique to the CI environment. I can't reproduce the failures locally e.g. when setting apm to be a git dependency.

Have to wonder why it's this complicated for git dependencies, but I supposethe publishing process usually strips oackage-lock.json and similar files... Which isn't the case in a bare git repo? But I would assume package-lock.json would be ingored... :shrug:

**Comment by DeeDeeG** [comment]
Not sure if this will help, but try with npm >= 6.14.2. Their dependency [`hosted-git-info`](https://github.com/npm/hosted-git-info#readme) was bumped a few times with various fixes. 

https://github.com/npm/cli/blob/latest/CHANGELOG.md#6142-2020-03-03

**Comment by aminya** [comment]
This line is causing issues:
https://github.com/atom/atom/blob/4a9d56f52cab00a22744858d4077600d5365197a/packages/incompatible-packages/lib/view-uri.js#L3

I can fix this. We just need to name export it.

**Comment by aminya** [comment]
Oh wow! Most of the tests have passed! 🎉 
I just need to fix the rest:
```js
##[error] The 'core-render-process for D:/a/1/s/spec/babel-spec.coffee.' test step finished with a non-zero exit code 
 You can run the test again using: 
	 D:/a/1/s/out/Atom Dev x64/atom-dev.exe --resource-path D:\a\1\s --test D:/a/1/s/spec/babel-spec.coffee
##[error] The 'core-render-process for D:/a/1/s/spec/compile-cache-spec.coffee.' test step finished with a non-zero exit code 
 You can run the test again using: 
```
These tests should actually be updated themselves.

**Comment by aminya** [comment]
So the problem is that the bundled code cannot find the babel plugins. I am not sure what is happening inside assar when electron-link bundles it. I might need to adjust babelrc

**Comment by aminya** [comment]
Including babel dependencies in the snapshot fails. I wonder if we can declare the babel dependencies as external.

**Comment by aminya** [comment]
I tried 4 different bundlers for bundling babel: https://github.com/atom-ide-community/babel-preset-atomic/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc

All of them fail. We need to find a way to declare babel as external, but let Atom call it during normal loading.

**Comment by aminya** [comment]
I found a way to make babel external. We need to have a folder called `externals` and keep every application that is supposed to be external there. This is similar to how `apm` has its own folder and `package.json`.

**Comment by aminya** [comment]
Putting the error message here for when I get back to this later:
```ps1
node-apm .\script\build
Node:   v12.4.0
Npm:    v6.14.8
Python: v3.8.5
Installing script dependencies
Installing apm
Installing modules done
Wrote Dependencies Fingerprint: C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\node_modules\.dependencies-fingerprint f5e4a7943fb21e13d43bb676626d3c91c45941db
Cleaning C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out
Copying assets to C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\app
Transpiling packages with custom transpiler configurations in C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\app
 transpiling for package github
Installing modules done
Transpiling Babel paths in C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\app
Transpiling CoffeeScript paths in C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\app
Transpiling CSON paths in C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\app
Transpiling PEG.js paths in C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\app
Generating module cache for C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\app
Generating pre-built less cache in C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\app\less-compile-cache
Generating metadata for C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\app\package.json
Generating API docs at C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\docs\output\atom-api.json
Skipping symbol dumping because minidump is not supported on Windows
Running electron-packager on C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\app with app name "atom-dev"
Packaging app for platform win32 x64 using electron v6.1.12
Copying non-ASAR resources to C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\Atom Dev x64\resources
Writing LICENSE.md to C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\Atom Dev x64\resources
Application bundle created at C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\Atom Dev x64
Generating snapshot script at "C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\startup.js" (2168)##[warning] C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\app\node_modules\less\lib\less-node\fs.js
The reference to the module is replaced with the lazy function, but it is assigned to "module" or "exports". In some cases the bundle might not work, which you should fix manually.
Generating snapshot script at "C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\startup.js" (3275)##[warning] C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\app\node_modules\react-relay\lib\ReactRelayQueryRenderer.js
The reference to the module is replaced with the lazy function, but it was not in an assignment expression or a variable declaration. In some cases the bundle might not work, which you should fix manually.
Generating snapshot script at "C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\startup.js" (4913)
Minifying startup script
Verifying if snapshot can be executed via `mksnapshot`
C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\startup.js:1
var snapshotAuxiliaryData={lessSourcesByRelativeFilePath:{"static\\atom-ui\\_index.less":{content:'// Atom UI\r\n\r\n// Private! Don\'t use these in packages.\r\n// If you need something, feel free to open an issue and it might can be made public\r\n@import "styles/private/scaffolding.less";\r\n\r\n@import "styles/private/alerts.less";\r\n@import "styles/private/close.less";\r\n@import "styles/private/code.less";\r\n@import "styles/private/forms.less";\r\n@import "styles/private/links.less";\r\n@import "styles/private/navs.less";\r\n@import "styles/private/sections.less";\r\n@import "styles/private/tables.less";\r\n@import "styles/private/utilities.less";\r\n\r\n\r\n// Public components\r\n// Open the Styleguide to see them in action\r\n@import "styles/badges.less";\r\n@import "styles/button-groups.less";\r\n@import "styles/buttons.less";\r\n@import "styles/git-status.less";\r\n@import "styles/icons.less";\r\n@import "style

Error: Cannot require module "../node_modules/@babel/runtime/helpers/interopRequireDefault.js".
To use Node's require you need to call `snapshotResult.setGlobals` first!
    at require (C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\startup.js:1:734603)
    at customRequire (C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\startup.js:1:735054)
    at get__interopRequireDefault (C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\startup.js:946:2902637)
    at get__inheritsLoose2 (C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\startup.js:946:2903694)
    at C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\startup.js:946:2903785
    at Object.../node_modules/react-relay/lib/ReactRelayQueryRenderer.js (C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\startup.js:946:2905781)
    at customRequire (C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\startup.js:1:734944)
    at Object.../node_modules/react-relay/lib/index.js (C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\startup.js:946:2530538)
    at customRequire (C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\startup.js:1:734944)
    at Object.../node_modules/react-relay/index.js (C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\startup.js:946:2113531)
Error: Command failed: C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\Atom Dev x64\atom-dev.exe C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\script\verify-snapshot-script C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\startup.js
C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\startup.js:1
var snapshotAuxiliaryData={lessSourcesByRelativeFilePath:{"static\\atom-ui\\_index.less":{content:'// Atom UI\r\n\r\n// Private! Don\'t use these in packages.\r\n// If you need something, feel free to open an issue and it might can be made public\r\n@import "styles/private/scaffolding.less";\r\n\r\n@import "styles/private/alerts.less";\r\n@import "styles/private/close.less";\r\n@import "styles/private/code.less";\r\n@import "styles/private/forms.less";\r\n@import "styles/private/links.less";\r\n@import "styles/private/navs.less";\r\n@import "styles/private/sections.less";\r\n@import "styles/private/tables.less";\r\n@import "styles/private/utilities.less";\r\n\r\n\r\n// Public components\r\n// Open the Styleguide to see them in action\r\n@import "styles/badges.less";\r\n@import "styles/button-groups.less";\r\n@import "styles/buttons.less";\r\n@import "styles/git-status.less";\r\n@import "styles/icons.less";\r\n@import "style

Error: Cannot require module "../node_modules/@babel/runtime/helpers/interopRequireDefault.js".
To use Node's require you need to call `snapshotResult.setGlobals` first!
    at require (C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\startup.js:1:734603)
    at customRequire (C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\startup.js:1:735054)
    at get__interopRequireDefault (C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\startup.js:946:2902637)
    at get__inheritsLoose2 (C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\startup.js:946:2903694)
    at C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\startup.js:946:2903785
    at Object.../node_modules/react-relay/lib/ReactRelayQueryRenderer.js (C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\startup.js:946:2905781)
    at customRequire (C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\startup.js:1:734944)
    at Object.../node_modules/react-relay/lib/index.js (C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\startup.js:946:2530538)
    at customRequire (C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\startup.js:1:734944)
    at Object.../node_modules/react-relay/index.js (C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\out\startup.js:946:2113531)

  at checkExecSyncError (child_process.js:616:11)
  at Object.execFileSync (child_process.js:634:15)
  at C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom\script\lib\generate-startup-snapshot.js:295:18


```

**Comment by aminya** [comment]
Atom now builds without issues 🎉 

The errors in the tests are because of babel-plugin-add-module-exports, which does not work properly in some cases. I need to update that.

**Comment by DeeDeeG** [comment]
Wow! That's great. It should mean we + upstream can potentially close https://github.com/atom/atom/issues/21091.

**Comment by aminya** [comment]
This is upstreamed to get more help: https://github.com/atom/atom/pull/21623

**Comment by aminya** [comment]
This works fine now. There might be some failing tests here and there that should be addressed.

**Comment by aminya** [comment]
This basically works fine now! 🎉

**Comment by aminya** [comment]
It seems that the find-and-replace package needs some updating.

**Review by aminya — COMMENTED** [review]
This is ready! 🎉 I am going to merge this tomorrow.

**Pull request merged**
