### PR TITLE
Migrate all language packages + Bump Tree Sitter [Duplicate] 

### PR DESCRIPTION
**Pull request by mauricioszabo**
Monorepo-ing language packages and bumping tree-sitter for all of them.

This PR is here to check what's wrong on the tests and try to fix them too

### CODE REVIEW

**Comment by aminya** [comment]
Please change the target branch to #450 so we can see what is the difference.

**Comment by aminya** [comment]
This is basically the same as #450. See the comments there.

**Comment by stech11845** [comment]
> This is basically the same as #416. See the comments there.

Please close @aminya this pull request.

**Comment by aminya** [comment]
Please reopen once you added a new change. The target branch should be #416

**Pull request closed without merging**
