### PR TITLE
➡️ Migrate all language packages

### PR DESCRIPTION
**Pull request by icecream17**
To make https://github.com/atom-community/atom/pull/386 reviewable, that pr will be separated into many simpler prs. This is one of them.

The first commit does the following:
- update package.json
- update package-lock.json using `./script/build` which also seems to update `apm/package-lock.json`
- update packages/README.md
- clone all language packages

I've added these repos to `packages` _but I'm not actually updating the package.json for these packages_:
* language-c
* language-css
* language-go
* language-javascript

Consequently they're **unused**. See the first commit for an explanation, but basically they're at tree-sitter v19 which currently breaks atom.

## Possible changes

A second commit or rebase could take care of these issues:

This would've/will be so useful:
This saves the commit history of the language-packages:
https://github.com/atom-community/atom/pull/386#issuecomment-1162267461
https://discord.com/channels/737254137690980372/809982257468801065/988156409977917510 

- [x] lint
- [ ] update packages/README.md again (change atom prs to point to atom, add this pr)

### CODE REVIEW

**Review by aminya — CHANGES_REQUESTED** [review]
Thanks for the work. Now, this is easier to manage.

Could you run `script/lint --fix`

**Comment by aminya** [comment]
Are the test failures relevant to these changes?

**Comment by ThatXliner** [comment]
Maybe add
```js
waitsForPromise(() => atom.packages.activatePackage(path.join(__dirname, 'fixtures', 'package-with-snippets')));
```
below https://github.com/atom/snippets/blob/b1ac84ef7dc988ee0417ad9c44f5dd397c929411/spec/snippet-loading-spec.js#L103

**Comment by ThatXliner** [comment]
Or it could be https://github.com/atom/snippets/commit/2de9091b3d6f5ba9889c448c929865aef960ffc5 

I guess it's just some sort of flaky test, I wonder happens if you try my suggestion

**Comment by aminya** [comment]
We can't add this here. I forked the repository. @ThatXliner do you want to try your fix?
https://github.com/atom-community/snippets

**Review by aminya — APPROVED** [review]
I will merge this regardless of the tests because they seem unrelated. Since this is not merging to master, it is fine.

**Pull request merged**
