### PR TITLE
remove logo guidelines badge

### PR DESCRIPTION
**Pull request by stech11845**
### Requirements for Contributing Documentation

* Fill out the template below. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* The pull request must only contribute documentation (for example, markdown files or API docs). To contribute other changes, you must use a different template. You can see all templates at <https://github.com/atom/.github/tree/master/.github/PULL_REQUEST_TEMPLATE>.

### Description of the Change
Removed the logo guidelines badge in README.

### Release Notes
N/A

### CODE REVIEW

**Comment by aminya** [comment]
Please add `[skip ci]` to the commit messages that only modify the docs.

**Review by aminya — COMMENTED** [review]
Until we change the icons to our own, we should keep these.

**Comment by stech11845** [comment]
> Until we change the icons to our own, we should keep these.

You have this icon:
atom-community-icon

**Comment by stech11845** [comment]
> Until we change the icons to our own, we should keep these.

But what about your GitHub organization logo? Like why? I mean this one:
atom-community-icon
So if it is not used in the software, then???

**Comment by aminya** [comment]
> > Until we change the icons to our own, we should keep these.
> 
> But what about your GitHub organization logo? Like why? I mean this one:
> atom-community-icon
> So if it is not used in the software, then???

We should do the work and change the icons before we remove the original guidelines.

**Pull request closed without merging**
