### PR TITLE
Put badges under Atom Community text [skip ci]

### PR DESCRIPTION
**Pull request by stech11845**
### Requirements for Contributing Documentation

* Fill out the template below. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* The pull request must only contribute documentation (for example, markdown files or API docs). To contribute other changes, you must use a different template. You can see all templates at <https://github.com/atom/.github/tree/master/.github/PULL_REQUEST_TEMPLATE>.

### Description of the Change
Put badges under the Readme Atom Community text.

### Release Notes
N/A

### CODE REVIEW

**Review by aminya — APPROVED** [review]

**Comment by ElectronicsArchiver** [comment]
Why though?

**Comment by stech11845** [comment]
> Why though?

@ElectronicsArchiver This is what I'm talking about...

It causes an inconsistency which is that the badges are at the top of the `h1` attribute that you specified in the Markdown code, and most projects put any badges/buttons **below** their project's `h1` attribute. So it makes sense to merge these changes.

**Comment by ElectronicsArchiver** [comment]
> It causes an inconsistency which is that the badges are at the top of the h1 attribute that you specified in the Markdown code, and most projects put any badges/buttons below their project's h1 attribute. So it makes sense to merge these changes.

- 'inconsistency' that inconveniences who? 

  I don't see how this is any sort of positive change to the design.

  

  In fact your change makes it even less consistant considering:

  - Badges & buttons are smushed together making it easier for users to confuse them

  - Badges are indicators that are commonly put on the edge of content not mixed within it, it's like you took the twitter, youtube,.. linked logos of a pages sidebar / footer and put them right in the article / post /..

  - It's just plain ugly I have to say

  - If you at least had put them at the bottom with the other badge..

  - If you wanted separation you should have just placed them before the banner

- 'most projects', statistical proof?

**Comment by stech11845** [comment]
> > It causes an inconsistency which is that the badges are at the top of the h1 attribute that you specified in the Markdown code, and most projects put any badges/buttons below their project's h1 attribute. So it makes sense to merge these changes.
> 
> * 'inconsistency' that inconveniences who?
>   I don't see how this is any sort of positive change to the design.
>   
>   In fact your change makes it even less consistant considering:
>   
>   * Badges & buttons are smushed together making it easier for users to confuse them
>   * Badges are indicators that are commonly put on the edge of content not mixed within it, it's like you took the twitter, youtube,.. linked logos of a pages sidebar / footer and put them right in the article / post /..
>   * It's just plain ugly I have to say
>   * If you at least had put them at the bottom with the other badge..
>   * If you wanted separation you should have just placed them before the banner
> * 'most projects', statistical proof?

@ElectronicsArchiver The badges look different than buttons. Look at the difference below
image

It is different. So I think it is ok to keep these changes.

**Comment by stech11845** [comment]
> I know they are different, I made them.
> 
> No, that does not resolve my critique.
> 
> @aminya Please tell me you see my problem with this.

Fine, i'll get it reversed

**Comment by stech11845** [comment]
> I prefer the current design because the more important buttons come first. The badges are not useful for most people.

So what?

**Comment by ElectronicsArchiver** [comment]
@aminya Then just look at any bigger website like https://www.youtube.com/, badges at the top.

**Comment by ElectronicsArchiver** [comment]
Also consider that more people would be interested in the discord than how to build or most parts of the documentation, doesn't help your case.

**Comment by stech11845** [comment]
> @aminya Then just look at any bigger website like https://www.youtube.com/, badges at the top.

Do you mean?
image

**Comment by aminya** [comment]
Most people want to download Atom and use it (used to be two million people). We only have a handful of developers who build Atom.

**Pull request merged**
