### PR TITLE
Bump tree sitter

### PR DESCRIPTION
**Pull request by mauricioszabo**
Please, merge after this PR otherwise grammars will break: https://github.com/atom-community/atom/pull/399

This PR bumps tree-sitter to a recent version. It also uses "NPM's tree sitter", not an Atom/git specific one.

I know this code works with Electron 12. Unfortunately, `./script/bootstrap` and friends do not work on my machine, so I have no way of testing if the "current way" of building Atom also works...

Also, this PR is basically https://github.com/atom-community/atom/pull/386, but splitted into bumping tree-sitter. I'll open another bumping Electron (but it's also dependent on this one, unfortunately)

### CODE REVIEW

**Comment by aminya** [comment]
Changed the target branch so we have some buffer to fix the tests before the final merge.

**Comment by aminya** [comment]
I cannot push to this branch. Could you enable push access?

**Comment by icecream17** [comment]
Btw, you might've not seen this note from my pr:
> I've added these repos to `packages` but _I'm not actually updating the package.json for these packages_:
>
> - language-c
> - language-css
> - language-go
> - language-javascript

I could update `package` and `package-lock` (if access is given)

**Comment by aminya** [comment]
@icecream17 What about merging it to our branch and then applying the changes on the repo we have access to?

**Comment by aminya** [comment]
I made a new PR based on our branch:
Here you go: https://github.com/atom-community/atom/pull/416

**Pull request merged**
