### PR TITLE
decaffinate and format

### PR DESCRIPTION
**Pull request by jeff-hykin**
just wanted to make a PR to run the tests

### CODE REVIEW

**Comment by aminya** [comment]
Please use decaffeinate instead of coffeescript itself

**Comment by jeff-hykin** [comment]
Well I was trying to first compile it the same way it was compiled for runtime so that correctness would be ensured. Then I was gradually going to get it closer to being human readable like decaffeinate does.

However it looks like even this first attempt failed to build :/ so I'll have to go back and try not formatting them at all this time.

**Comment by aminya** [comment]
That's because you used CoffeeScript 2, which has some breaking changes compared to v1.

**Comment by jeff-hykin** [comment]
Oh, I didn't realize Atom used v1. Thanks, that would've taken me forever to figure out

**Comment by aminya** [comment]
I think we already discussed that acpm is not the way we want to go forward with apm. Since the decaffination part is automatic, we can recreate this incrementally.

**Review by aminya — CHANGES_REQUESTED** [review]
I think we already discussed that acpm is not the way we want to go forward with apm. Since the decaffination part is automatic, we can recreate this incrementally.

**Pull request closed without merging**
