### PR TITLE
Add commits behind

### PR DESCRIPTION
**Pull request by softorangetech11**
This adds the commits behind.

### CODE REVIEW

**Review by kaosine — CHANGES_REQUESTED** [review]
With the readme.md we removed that wording for a reason. We're moving away from the atom naming and trying to distance ourself from them.

**Comment by softorangetech11** [comment]
> With the readme.md we removed that wording for a reason. We're moving away from the atom naming and trying to distance ourself from them.

What wording? I have not seen the wording.

**Comment by DeeDeeG** [comment]
I this does re-add the sunset text for some reason, we can revert that.

All this Pr is doing is adding the commits from upstream that we didn't merge yet.

I would like to see CI pass, not sure why it didn't. I'm trying to re-run it.

**Comment by DeeDeeG** [comment]
Ah, okay, this needs merge conflicts resolved.

**Comment by DeeDeeG** [comment]
This would need changes, github.com will not allow this to be merged (the merge button is grayed out), unless the merge conflicts are solved.

We will want to close this and re-open as a pull request from our fork's `upstream_master` branch (https://github.com/atom-community/atom/tree/upstream_master) to our fork's `master` branch. Then we can fix the conflicts and merge it.

Thanks for the PR @softorangetech11, let me know if you want to try it again from `upstream_master` branch, or if you want one of us to do it.

Best Regards.

**Comment by softorangetech11** [comment]
@DeeDeeG I closed this for your convenience.

**Comment by softorangetech11** [comment]
@DeeDeeG You can try `upstream_master` this would be better since the upstream has some stuff.

**Pull request closed without merging**
