### PR TITLE
Updated pipeline badge in README and install details

### PR DESCRIPTION
**Pull request by slashtechno**
### Updated pipeline badge in README  and install details
I updated the pipeline badge and install details in order to clarify the process of installing binaries produced by code created by the Atom Community.

### CODE REVIEW

**Comment by DeeDeeG** [comment]
We should point people to `https://dev.azure.com/atomcommunity/atomcommunity/_build/latest?definitionId=10&branchName=master` and from there select "8 published" and so on.

**Comment by slashtechno** [comment]
> 

Okay, I will add the original text as a comment

**Comment by DeeDeeG** [comment]
You know, we can set up Nightly builds again if people want. (https://github.com/atom-community/atom-nightly-releases). That would be a lot tidier than grabbing from Azure Pipelines...

**Comment by slashtechno** [comment]
Okay, I added the original steps as a comment. Should nightly builds be set up now and added to the documentation in this PR or a separate PR?

**Comment by DeeDeeG** [comment]
Turning on Nightly builds is mostly a CI config thing over at Azure Pipelines. That's another concern. Ready to merge this soon.

Do you mind if I squash the commits together to one commit?

**Comment by slashtechno** [comment]
> Turning on Nightly builds is mostly a CI config thing over at Azure Pipelines. That's another concern. Ready to merge this soon.
> 
> Do you mind if I squash the commits together to one commit?

No problem. How does merging commits to form one commit work though?

**Comment by DeeDeeG** [comment]
Also, we don't need this sentence anymore: "From this pipeline, the latest run can be selected." The new link automatically redirects to the latest run.

Sorry for all the small changes, I can do that change if you want when merging.

Thanks.

**Comment by DeeDeeG** [comment]
Merging multiple commits takes the changes cumulatively made by all the commits, and records that as the diff.

New commit message has to be composed manually.

I think the author date uses one of the author dates for the squashed commits?? Or maybe just the time of squashing. Commit date becomes the time you squash. Author is the original author, committer becomes the person who squashed.

Basically it is as if the change set was composed as one commit the whole time. "Re-writing the history" a bit. A lot more details can be ha here: https://www.git-tower.com/learn/git/faq/git-squash/

**Comment by DeeDeeG** [comment]
Pushing a commit or two to your branch, if you don't mind, so that they become part of this PR? Just removing the extra sentence, and making the comments a little more prominent to notice in the source. Doesn't affect the output.

<details>

```diff
diff --git a/README.md b/README.md
index 6be3678fc..2821611b0 100644
--- a/README.md
+++ b/README.md
@@ -28,7 +28,9 @@ If you want to read about using Atom or developing packages in Atom, the [Atom F
 The [API reference](https://atom.io/docs/api) for developing packages is also documented on Atom.io.
 
 ## Installing
-<!-- ### Prerequisites
+
+<!-- ~BEGIN COMMENTED OUT OLD INSTALL INSTRUCTIONS~
+### Prerequisites
 - [Git](https://git-scm.com)
 
 ### macOS
@@ -70,8 +72,10 @@ sudo apt install git libasound2 libcurl4 libgbm1 libgcrypt20 libgtk-3-0 libnotif
 4. Launch Atom using the installed `atom` command from the newly extracted directory.
 
 The Linux version does not currently automatically update so you will need to
-repeat these steps to upgrade to future releases. -->
-Currently, to get binaries based on code by the Atom community, binaries can be downloaded from the [Azure Pipeline](https://dev.azure.com/atomcommunity/atomcommunity/_build/latest?definitionId=10&branchName=master). From this pipeline, the latest run can be selected. From there, the `8 published` link should be selected to download the files.  
+repeat these steps to upgrade to future releases.
+~END COMMENTED OUT OLD INSTALL INSTRUCTIONS~ -->
+
+Currently, to get binaries based on code by the Atom community, binaries can be downloaded from the [Azure Pipeline](https://dev.azure.com/atomcommunity/atomcommunity/_build/latest?definitionId=10&branchName=master). From there, the `8 published` link should be selected to download the files.
 
 ## Building
 
```

</details>

**Comment by DeeDeeG** [comment]
Okay, looks like I don't have permissions at this repo to merge pull requests at the moment. Will find the folks who do and discuss with them.

**Comment by kaosine** [comment]
Well with releases it probably would help to figure out that release schedule anyways. It would probably help to do something like:

- nightly
- development published every 2 or so weeks
- stable pushed when certain milestones are met

I don't know where we'd call that line right now being at 1.63 or wherever those lines are drawn however. Though maybe also file when the bot checks merges as snapshots?

**Comment by slashtechno** [comment]
> Okay, looks like I don't have permissions at this repo to merge pull requests at the moment. Will find the folks who do and discuss with them.

Okay

**Comment by autumnblazey** [comment]
> > Turning on Nightly builds is mostly a CI config thing over at Azure Pipelines. That's another concern. Ready to merge this soon.
> > Do you mind if I squash the commits together to one commit?
> 
> No problem. How does merging commits to form one commit work though?

Github website gives a "squash and merge" option when merging PRs, you can choose it from a little dropdown arrow next to the merge button. It gives you an option of commit message and author and etc as always

**Comment by slashtechno** [comment]
> > > Turning on Nightly builds is mostly a CI config thing over at Azure Pipelines. That's another concern. Ready to merge this soon.
> > > Do you mind if I squash the commits together to one commit?
> > 
> > 
> > No problem. How does merging commits to form one commit work though?
> 
> Github website gives a "squash and merge" option when merging PRs, you can choose it from a little dropdown arrow next to the merge button. It gives you an option of commit message and author and etc as always

Oh okay, I never noticed the dropdown

**Review by aminya — APPROVED** [review]

**Pull request merged**
