### PR TITLE
Simpler installation instructions

### PR DESCRIPTION
**Pull request by LorenzoAncora**
### Description of the Change

Free software developers aren't necessarily familiar with Azure. This PR makes the instructions clearer and more verbose, making the download process easier.

### Release Notes

The installation instructions are now much easier to understand.

### CODE REVIEW

**Comment by DeeDeeG** [comment]
By the way, I was meaning to suggest this be added: https://autumnblazey.github.io/atomcommunity-pipelines/

It's a nice dashboard created by @autumnblazey to make getting the binaries much easier.

**Review by aminya — APPROVED** [review]

**Comment by LorenzoAncora** [comment]
@DeeDeeG Azure is not the place for end users.
I suggest that _Atom Community_ needs its own dedicated website, to build the trust of the community and gain popularity as the de facto replacement for Atom. This website should be maintained by the project owners and offer a big "Download latest version" button, alongside a friendly changelog and maybe a simple RSS feed.

**Comment by stech11845** [comment]
> @DeeDeeG Azure is not the place for end users. I suggest that _Atom Community_ needs its own dedicated website, to build the trust of the community and gain popularity as the de facto replacement for Atom. This website should be maintained by the project owners and offer a big "Download latest version" button, alongside a friendly changelog and maybe a simple RSS feed.

There's an atom-community/website repository.

**Comment by LorenzoAncora** [comment]
> There's an atom-community/website repository.

@stech11845 to gain popularity, a fork must appear on Google SERP and offer a simple way to download the most appropriate installer from a trusted domain. Searching for "Atom Community" on Google or DDG does not return any dedicated website. Clearly, that repository you referred to contains a basic, static website which is not yet online.

**Comment by aminya** [comment]
Added the website here:
https://atom-community.github.io/

@autumnblazey could you make a PR to add the download links to the website?

**Comment by LorenzoAncora** [comment]
> Added the website here: https://atom-community.github.io/
> @autumnblazey could you make a PR to add the download links to the website? https://github.com/atom-community/atom-community.github.io

Wise choice, albeit I'm sure you'll feel the need to get your own `.io` or `.com` domain in future. With a static website you won't need paid hosting.
Regardless, it would be nice to:

- limit the download choices to only 3 buttons (eg. installer for Windows, installer for Linux, installer for Mac) on the home page;
- specify on the home page that you are offering this entire community-maintained fork of Atom and not only some packages. Now that Atom is being abandoned, people is likely searching for a replacement which will be kept up-to-date.

If you need help with the layout, feel free to ask and I'll happily lend a hand.

**Pull request merged**
